### ISSUE TITLE
(P.7) Requirements process and report

### ISSUE THREAD

**Issue by mosser** [ace-lectures/atco-eats#11]
Initially, description of what the requirements process will be; later, report on its steps. It starts out as a plan for conducting the requirements elicitation process, but is meant to be updated as part of that process so that it includes the key lessons of elicitation.

**Comment by t-chiang** [comment]
.. community, and whant -> and want

We will use this question as opener, and bounce on the different topics thje interviewee might raise to gather as many feedback as possible.
->
We will use this question as an opener and bounce between the different topics the interviewee might raise to gather as much feedback as possible

... what dimensions drives your choice -> what aspects affect your choice

.. help clarifying the ambiguity -> help to clarify the ambiguity

.. the project developers has. -> the project developers have.
