### ISSUE TITLE
(G.5) High-level usage scenarios

### ISSUE THREAD

**Issue by mosser** [ace-lectures/atco-eats#12]
Fundamental usage paths through the system. It presents the main scenarios (use cases) that the system should cover. The scenarios chosen for appearing here, in the Goals book, should only be the **main usage patterns**, without details such as special and erroneous cases; they should be stated in user terms only, independently of the system's structure. Detailed usage scenarios, taking into account system details and special cases, will appear in the System book (<<s4>>).

**Comment by mosser** [comment]
- I cannot find things related to reporting in Appendix A (relation with client). It was part of the initial discussion, but after the ideation workshop, it looks like they have re-centred their expectations.
- I'm wondering about the scope of the system concerning some use cases. 
  - Is it part of ATCO to support food processing (e.g., line cook use cases)?
  - Should Mosaic/Payment Gateway be considered as system actors?
  - Citizen + community members could be abstracted as patrons to factorize the first relations
  - I cannot find a relation to "order food" for the citizen persona description. Is it part of scope to order food for this actor? Same for payment (except to get some free food with points)
    - _(We really need to clarify with TheFirebird what are the perks associated to Loyalty points.)_
  - Is the process payment use case related to Manager rather than admin assistant? I'd guess the manager will send the invoice to Mac through ATCO, but based on the assistant description it should be transparent on their side.

**Comment by mosser** [comment]
According to instructions, use cases should come with a high-level description of their scenario (5-6 steps)

**Comment by t-chiang** [comment]
Need to add details for the use cases

**Comment by mosser** [comment]
Proposal to update use cases

![Image](https://github.com/ace-lectures/atco-eats/assets/379602/8b4a6c94-982a-47b3-b665-de5a5f3aca2e)

**Comment by mosser** [comment]
Text slightly rewritten to align with the new UC model (model also fixed for one inclusion: order include pay)

**Comment by t-chiang** [comment]
All looks great
