### ISSUE TITLE
(E.3) Constraints

### ISSUE THREAD

**Issue by mosser** [ace-lectures/atco-eats#13]
Obligations and limits imposed on the project and system by the environment. This chapter defines non-negotiable restrictions coming from the environment (business rules, physical laws, engineering decisions), which the development will have to take into account.

**Comment by mosser** [comment]
I had to add some constraints related to mosaic.

**Comment by mosser** [comment]
- "_in the event that customers do no wish to download the app_". 
  - Does it means that we should develop a web app for the patrons too, in addition to the mobile one?
  - Or is it triggering a tech constraint that we'll have to use a platform-independent (webn+mobils) system such as Flutter?

**Comment by t-chiang** [comment]
Update S4 Usage 5: Hamilton Citizen wants to have picnic at cootes

This also supports having a web browser version separate from app without loyalty program

**Comment by mosser** [comment]
Added: "(_i.e._, Chrome, Safari, Edge)" to "The system must work with internet browsers ".
