### ISSUE TITLE
(S.3) Interfaces

### ISSUE THREAD

**Issue by mosser** [ace-lectures/atco-eats#18]
How the system makes the functionality of <<s2>> available to the rest of the world, particularly user interfaces and program interfaces (APIs). It specifies how that functionality will be made available to the rest of the world, including people (users) and other systems. These are interfaces provided by the system to the outside; the other way around, interfaces from other systems, which the system may use, are specified in <<e2>>.

**Comment by t-chiang** [comment]
PendingInvoice. thisn interface is -> PendingInvoice. This interface is

integrate the systemn with Mosaic, -> integrate the system with Mosaic,

have access quickly to -> have quick access to

Love the Flush! idea
