### ISSUE TITLE
(S.6) Verification and acceptance criteria

### ISSUE THREAD

**Issue by mosser** [ace-lectures/atco-eats#20]
Specification of the conditions under which an implementation will be deemed satisfactory. Here, "verification" as shorthand for what is more explicitly called "Verification & Validation" (V&V), covering several levels of testing — module testing, integration testing, system testing, user acceptance testing — as well as other techniques such as static analysis and, when applicable, program proving.

**Comment by mosser** [comment]
Need to stabilize the NF requirements for the second part.

**Comment by mosser** [comment]
S6 (draft) is written assuming four NF properties: Accessibility, privacy, security and accounting compliance.

**Comment by t-chiang** [comment]
We will take measure when -> We will take measures when

Such audit will be part -> This audit will be part
