### ISSUE TITLE
(G.7) Stakeholders and requirements sources

### ISSUE THREAD

**Issue by mosser** [ace-lectures/atco-eats#3]
Groups of people who can affect the project or be affected by it, and other places to consider for information about the project and system. It lists stakeholders and other requirements sources. It should define stakeholders as categories of people, not individuals, even if such individuals are known at the time of writing. The main goal of chapter <<g7>> is to avoid forgetting any category of people whose input is relevant to the project. It also lists documents and other information that the project, aside from soliciting input from stakeholders, can consult for requirements information.

**Comment by t-chiang** [comment]
... time betweeb -> between

... and work as assistant -> and works as an assistant

.. have to teenager children -> two teenage children

... hired to help adapting -> hired to help adapt

Dylan works as a... -> Dylan has worked as a...
