### ISSUE TITLE
(E.5) Effects

### ISSUE THREAD

**Issue by mosser** [ace-lectures/atco-eats#8]
Elements and properties of the environment that the system will affect. It defines effects of the system's operations on properties of the environment. Where the previous two categories (<<e3>>, <<e4>>) defined influences of the environment on the system, effects are influences in the reverse direction.

**Comment by mosser** [comment]
@t-chiang Maybe we're missing a "how" to make the influence more explicit?
- Increase in student happiness, health, and morale **by ...**
- Increase in on-campus student population **by ...**
- Increase in events on campus **by ...**
- 
Our guidelines says (2 sentences/item, so we could add it)

**Comment by t-chiang** [comment]
New push that addressed the how for the potential effects
